### ISSUE TITLE
Права коммита

### ISSUE THREAD

**Issue by kobezzza** [typograf/grunt-typograf#2]
Может нужно отдельно для репозитария дать права, чтобы я мог коммитить? Сейчас не получается.

**Comment by hcodes** [comment]
Добавил к репозитариям группу "Админ", доступ должен появиться.
Можешь проверить?

**Comment by kobezzza** [comment]
Угу, теперь всё ок :smile:

**Comment by hcodes** [comment]
А в npm кому нужно добавить тебе или мне?

**Comment by kobezzza** [comment]
> А в npm кому нужно добавить тебе или мне?

Могу я сделать, ты проверил, всё ок?

**Comment by hcodes** [comment]
Всё ок!
