### ISSUE TITLE
Надо оформить релиз

### ISSUE THREAD

**Issue by kobezzza** [typograf/grunt-typograf#3]
Если всё ок, то надо сделать релиз и добавить его в npm.

**Comment by kobezzza** [comment]
Готово.

**Comment by hcodes** [comment]
Спасибо!

Добавил в README секцию со ссылками на плагины - https://github.com/typograf/typograf#%D0%9F%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D1%8B.
